#sudo permissions for installing docker
sudo: required

#installing docker
services:
  - docker

#this instruction happens before installing
before_install:
  - docker build -t moiscye/docker-react -f Dockerfile.dev .
  #telling travis to run our test. CI-true needed to end the test after finish it
script:
  - docker run -e CI=true moiscye/docker-react npm run test
